In [1]:
import numpy as np

In [2]:
a=10
print(a,type(a))
print("-"*50)
x=np.array(a)
print(x,type(x))
print("data type of x",x.dtype)
print("dimention of x",x.ndim)
print("dimention of x",x.shape)
print("dimention of x",x.size)




10 <class 'int'>
--------------------------------------------------
10 <class 'numpy.ndarray'>
data type of x int64
dimention of x 0
dimention of x ()
dimention of x 1


In [3]:
a="python"
print(a,type(a))
print("-"*50)
x=np.array(a)
print(x,type(x))
print("data type of x",x.dtype)
print("dimention of x",x.ndim)
print("dimention of x",x.shape)
print("dimention of x",x.size)

python <class 'str'>
--------------------------------------------------
python <class 'numpy.ndarray'>
data type of x <U6
dimention of x 0
dimention of x ()
dimention of x 1


In [7]:
a=range(12)
print(a,type(a))
for i in a:
    print(i)

range(0, 12) <class 'range'>
0
1
2
3
4
5
6
7
8
9
10
11


In [9]:

print(a,type(a))
print("-"*50)
x=np.array(a)
print(x,type(x))
print("data type of x",x.dtype)
print("dimention of x",x.ndim)
print("shape of x",x.shape)
print("size of x",x.size)

range(0, 12) <class 'range'>
--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11] <class 'numpy.ndarray'>
data type of x int64
dimention of x 1
shape of x (12,)
size of x 12


In [10]:
print(a,type(a))
print("-"*50)
x=np.array(a,dtype=float)
print(x,type(x))
print("data type of x",x.dtype)
print("dimention of x",x.ndim)
print("shape of x",x.shape)
print("size of x",x.size)

range(0, 12) <class 'range'>
--------------------------------------------------
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.] <class 'numpy.ndarray'>
data type of x float64
dimention of x 1
shape of x (12,)
size of x 12


In [11]:
a=range(1,21,2)
print(a,type(a))
print("-"*50)
x=np.array(a,dtype=float)
print(x,type(x))
print("data type of x",x.dtype)
print("dimention of x",x.ndim)
print("shape of x",x.shape)
print("size of x",x.size)

range(1, 21, 2) <class 'range'>
--------------------------------------------------
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.] <class 'numpy.ndarray'>
data type of x float64
dimention of x 1
shape of x (10,)
size of x 10
